// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlaviyxuffycemvuuzqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsYXZpeXh1ZmZ5Y2VtdnV1enFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMDQ5NDcsImV4cCI6MjA3MjY4MDk0N30.cl_yttyFauYtGlXybHtclaXjfeM7MVvk8q4G1vwS1I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});